// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("DiamondCS")]
[assembly: AssemblyProductAttribute("PropertyBasedTestingInFSharp")]
[assembly: AssemblyDescriptionAttribute("A short example of property based testing using F#")]
[assembly: AssemblyVersionAttribute("1.0")]
[assembly: AssemblyFileVersionAttribute("1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0";
        internal const string InformationalVersion = "1.0";
    }
}
