#I "./bin/Debug"

#r "FSharp.Core.dll"
#r "Foq.dll"
#r "FsCheck.NUnit.Addin.dll"
#r "FsCheck.NUnit.dll"
#r "FsCheck.dll"
#r "Microsoft.Owin.dll"
#r "Owin.dll"
#r "StatsdClient.dll"
#r "log4net.dll"
#r "nunit.core.dll"
#r "nunit.core.interfaces.dll"
#r "nunit.framework.dll"
#r "nunit.util.dll"
#r "CSharpDomain.dll"