// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("CSharpDomain")]
[assembly: AssemblyProductAttribute("PropertyBasedTestingInFSharp")]
[assembly: AssemblyDescriptionAttribute("A short example of property based testing using F#")]
[assembly: AssemblyVersionAttribute("0.1")]
[assembly: AssemblyFileVersionAttribute("0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1";
        internal const string InformationalVersion = "0.1";
    }
}
